### ISSUE TITLE
有问题

### ISSUE THREAD

**Issue by yestianxu** [ZhongXiaoHong/superFileView#1]
demo 只打开了PPT
其他格式都是失败呢 兄弟

**Comment by yestianxu** [comment]
xlsx也打开了- -

**Comment by yestianxu** [comment]
估计文档有空格吧。word 打开了 我的锅兄弟

**Comment by yestianxu** [comment]
可以的兄弟。不过还是有少许文档打不开。不明原因 已经很好了。

**Comment by ZhongXiaoHong** [comment]
什么文档打不开   可有错误提示  麻烦贴上来看一下

**Comment by goocher** [comment]
为什么打出来日志说 09-27 14:00:46.358 18658-18658/com.silang.superfileview E/TbsReaderView: not supported by:doc

**Comment by goocher** [comment]
我试了试，pptx的也报不支持错误，打开一片空白
