### ISSUE TITLE
在进入到页面后,右下角会有 最近文件和编辑 两个按钮,请问如何隐藏呢

### ISSUE THREAD

**Issue by yizeliang** [ZhongXiaoHong/superFileView#11]
在进入到页面后,右下角会有 最近文件和编辑 两个按钮,请问如何隐藏呢

**Comment by littleKun** [comment]
+1

**Comment by abczxtzxt** [comment]
++1，我也想问

**Comment by abczxtzxt** [comment]
第一次调用mSuperFileView.displayFile（path）之后 第二次在调用这个方法就打不开了，一直在转，提示正在加载文档？这个是什么问题呢

**Comment by Suppermanone** [comment]
+1，也想把那两个按钮隐藏了

**Comment by kenboos** [comment]
解决的大神，回复下呗、

**Comment by Zooc** [comment]
遍历ReaderView下的所有子View，找到MenuView及其下面的TextView，然后设置为隐藏即可

**Comment by ZhongXiaoHong** [comment]
模拟一个滑动事件   传给SuperFileView的TbsReaderView

**Comment by dongfangmingjia** [comment]
请问怎么模拟，怎么传给SuperFileView的TbsReaderView
