### ISSUE TITLE
在同一个界面不能重复打开文档

### ISSUE THREAD

**Issue by waibozi** [ZhongXiaoHong/superFileView#13]
第一次打开成功，选择其他文档后重新加载不出来，提示

invokeInstance -- exceptions:java.lang.NoSuchMethodException: onCallBackAction [class java.lang.Integer, class java.lang.Object, class java.lang.Object]

这个错误，能看看吗

**Comment by onecoders** [comment]
> 第一次打开成功，选择其他文档后重新加载不出来，提示
> 
> invokeInstance -- exceptions:java.lang.NoSuchMethodException: onCallBackAction [class java.lang.Integer, class java.lang.Object, class java.lang.Object]
> 
> 这个错误，能看看吗

请问，这个问题是怎么解决的？
