### ISSUE TITLE
插件加载失败

### ISSUE THREAD

**Issue by CristianoLi** [ZhongXiaoHong/superFileView#14]
提示“64-bit mode is not supported by x5, to solve the problem please refer to : https://x5.tencent.com/tbs/technical.html#/detail/sdk/1/34cf1488-7dc2-41ca-a77f-0014112bcab7”，但是我就是按照上面的方法添加的，一直报这个错误

**Comment by ZhongXiaoHong** [comment]
见 https://github.com/ZhongXiaoHong/superFileView/issues/10
