### ISSUE TITLE
如果手机没有装QQ，是不是不能用

### ISSUE THREAD

**Issue by BigBangbrother** [ZhongXiaoHong/superFileView#16]
我在一个新手机上，什么都打不开，只有log打印了一个不支持

**Comment by JeremyLeeL** [comment]
同问：E/TbsReaderView: not supported by:docx

**Comment by JeremyLeeL** [comment]
在Application中加了一段代码：QbSdk.initX5Environment(this, new QbSdk.PreInitCallback() {
			@Override
			public void onCoreInitFinished() {

			}

			@Override
			public void onViewInitFinished(boolean b) {
				Log.e(TAG, "X5内核初始化：" + b);
			}
		});
第二个参数可以直接传null

**Comment by chenkexu** [comment]
@JeremyLeeL 你的其他手机出现Bug了吗？

**Comment by JeremyLeeL** [comment]
@chenkexu 其他手机没有出现，这个bug是在三星手机上出现的，就是因为没有init X5，具体啥原因我没有深究
