### ISSUE TITLE
中文PDF文件打开异常，提示TbsReaderView: not supported by:pdf

### ISSUE THREAD

**Issue by coding404** [ZhongXiaoHong/superFileView#23]
中文PDF文件打开异常，提示TbsReaderView: not supported by:pdf

**Comment by TonyEasy** [comment]
同样遇到了word和excel打不开的情况

**Comment by ZhongXiaoHong** [comment]
见 issure10  和Readme

**Comment by GeekBugs** [comment]
这应该是TBS缓存的问题，可以当preOpen返回false的时候调用QbSdk.clearAllWebViewCache(context, true)
