### ISSUE TITLE
是不是8.1的系统用不了了。

### ISSUE THREAD

**Issue by etenel** [ZhongXiaoHong/superFileView#27]
我qq都打不开word文档了。用别的手机可以打开

**Comment by xiaobaDev** [comment]
你有用demo试过吗？

**Comment by etenel** [comment]
试了。日志显示不支持。

2018年1月18日 下午2:23，"kimmy" <notifications@github.com>写道：

**Comment by xiaobaDev** [comment]
8.0的支持吗？我试过也不行啊

**Comment by etenel** [comment]
那应该8.0以上的用不了了。试试QQ能不能打开word文件就知道了。我的QQ是打不开。😂等腾讯适配吧

2018年1月19日 上午9:23，"kimmy" <notifications@github.com>写道：

**Comment by etenel** [comment]
腾讯支持8.0了。我的8.1系统可以打开文件了

**Comment by xiaobaDev** [comment]
我们sdk要升级吗？还是他tbs内核会自动升级

**Comment by etenel** [comment]
我没升级SDK就可以用了。可能是它QQ或者微信带的内核升级了

2018年2月3日 下午10:39，"kimmy" <notifications@github.com>写道：
