### ISSUE TITLE
打开文本文档和PPT文档有一些bug。

### ISSUE THREAD

**Issue by wondersky-hy** [ZhongXiaoHong/superFileView#33]
有的文本文档打开会重复显示里面的内容；还有在打开PPT的时候，有时候能正常显示，但是有时候就显示不出来，屏幕就一片灰啥都没有，返回到上一界面再重新打开有概率会正常显示。
楼主设置什么原因？求解。

**Comment by ZhongXiaoHong** [comment]
你好  你是打开这个demo遇到这个情况还是你自己的demo遇到呢   有没有相关日志提示

**Comment by wondersky-hy** [comment]
这是在我自己的demo上碰到的，打开txt文件（重复显示就是先把里面的内容完整显示完，然后在末尾处重复显示文章开始处截取的一段内容）logcat上报这个warning：（ 我用了MultiDex拆包，不知道是不是因为这个问题。）

03-20 09:38:35.233 20779-20779/com.gcit.mobile W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mtt.external.reader.IReaderPurchaseView" on path: DexPathList[[zip file "/data/user/0/com.gcit.mobile/app_tbs/share/plugins/com.tencent.qb.plugin.txt/mttreader.jar"],

打开PPT文件的时候logcat也会出一个warning（不知道bug是不是跟这个warning有关）：
03-20 09:53:58.897 20779-21389/com.gcit.mobile W/System.err: org.xml.sax.SAXException: No input specified.
03-20 09:53:58.897 20779-21389/com.gcit.mobile W/System.err:     
at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:288)
03-20 09:53:58.897 20779-21389/com.gcit.mobile W/System.err:     
at com.hfdocument.e.b.e.hw(SourceFile:788)
03-20 09:53:58.897 20779-21389/com.gcit.mobile W/System.err:     
at com.hfdocument.e.b.e.hv(SourceFile:767)
03-20 09:53:58.897 20779-21389/com.gcit.mobile W/System.err:     
at com.hfdocument.e.b.e.R(SourceFile:175)
03-20 09:53:58.897 20779-21389/com.gcit.mobile W/System.err:     
at com.hfdocument.h.a.c.ay(SourceFile:102)
03-20 09:53:58.897 20779-21389/com.gcit.mobile W/System.err:     
at com.hfdocument.h.a.g.ig(SourceFile:186)
03-20 09:53:58.897 20779-21389/com.gcit.mobile W/System.err:     
at com.hfdocument.h.a.g.b(SourceFile:29)
03-20 09:53:58.897 20779-21389/com.gcit.mobile W/System.err:    
at com.hfdocument.h.a.j.run(SourceFile:304)
03-20 09:53:58.897 20779-21389/com.gcit.mobile W/System.err:     
at java.lang.Thread.run(Thread.java:833)

打开其他的如：xlxs，word，pdf都是正常显示log.i日志，文件也能正常打开没什么问题，不过在使用的时候每天第一次打开app查看文档的时候有时候会提示打开失败（文件已确认是下载在手里文件目录里的），返回上一界面然后第二次打开这三个类型的文件又能正常打开，这个是不是第一次打开的时候显示这些文件的组件没有加载好的问题？

**Comment by ZhongXiaoHong** [comment]
java.lang.ClassNotFoundException: Didn't find class "com.tencent.mtt.external.reader.IReaderPurchaseView" ----->提示你找不到这个类，从你的描述来看应该就是你分包导致的问题，你可以把这个类添加到主包上去

**Comment by wondersky-hy** [comment]
添加到主包上去还是报这个问题啊，我在jar包的目录里面好像没找到这个类。
