### ISSUE TITLE
tbs文件阅读器问题

### ISSUE THREAD

**Issue by william198824** [ZhongXiaoHong/superFileView#4]
之前我也使用过tbs作为文件阅读器，但是为什么我用的时候，文件浏览页面都会有下载qq浏览器的链接，而你这里却没有呢？

**Comment by ZhongXiaoHong** [comment]
恩   之前你使用tbs是用来浏览什么文件     比如ppt的放映功能  tbs是不支持的   当你需要放映的时候回提示你下载QQ浏览器    这个你可以往自己的手机QQ传一份ppt文件测试一下     其他的文件只是展示的话没有提示要下载QQ浏览器

**Comment by william198824** [comment]
可能是咱俩的sdk版本不一样，我的ppt是可以播放的，只有需要编辑的时候才会提示下载qq浏览器。而且我这边不管什么文件，单纯浏览查看的时候都会有qq浏览器字样。。。
等我有时间看看你的代码，找找咱俩之间的区别吧。
另外我的想法是，不知道能不能把tbs的文件功能单独提出来，要不然它不支持64位App，这点挺困扰。
