### ISSUE TITLE
Demo 网络下载查看有点问题

### ISSUE THREAD

**Issue by jw10041229** [ZhongXiaoHong/superFileView#7]
首先，非常感谢楼主的Demo！
原Demo中的网络下载发现下载失败，查看了一下log,发现楼主创建了一个007的文件夹，下载的文件却扔进了10086的文件夹中，故扔出异常！
FileDisplayActivity类 185行 007 ->10086

**Comment by ZhongXiaoHong** [comment]
@jw10041229   已经改过来    是我粗心了   谢谢告知
