### ISSUE TITLE
右下角的提示（“最近文件”，“放映”，“编辑”）之类的功能怎么调用？或者怎么去掉这个提示？谢谢

### ISSUE THREAD

**Issue by jamesChenXinxin** [ZhongXiaoHong/superFileView#8]

**Comment by ZhongXiaoHong** [comment]
放映编辑的能力  tbs  不具备   需要手机有安装QQ浏览器  这个你可以往手机QQ丢一个ppt文件    点击放映按钮会提示你下载QQ浏览器

**Comment by jamesChenXinxin** [comment]
那右下角的这些提示，可以把它们隐藏了吗？如可以，怎么做，找了好久，没看到。。。。

**Comment by xiang23** [comment]
有人找到怎么隐藏吗？

**Comment by bauer-bao** [comment]
同问

**Comment by kenboos** [comment]
有解决的么？回复下呗

**Comment by xiaobaDev** [comment]
直接用黑科技啊，打印出节点位置，找到后gone掉就好了啊
![tim 20180118142728](https://user-images.githubusercontent.com/5645220/35083774-ba9adaf2-fc5b-11e7-80e4-ec68db936e28.png)
